database:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/openregister_java
  user: postgres
  password:

  #db connection properties
  initialSize: 1
  minSize: 1
  maxSize: 4

  properties:
    charSet: UTF-8

server:
  registerDefaultExceptionMappers: false
  adminConnectors:
    - type: http
      port: 9092

registerDomain: openregister.dev:8080

register:
  entry-number: "18"
  item-hash: "sha-256:1e7aa55e22668057e21c4de7f7c897c50a244af814a5b682757316631b63b771"
  entry-timestamp: "2016-04-21T10:14:21Z"
  text: "Primary, secondary and special needs schools in England and Wales"
  phase: "alpha"
  fields:
  - "school"
  - "name"
  - "start-date"
  - "end-date"
  - "gender"
  - "religious-character"
  - "minimum-age"
  - "maximum-age"
  - "headteacher"
  - "website"
  - "address"
  register: "school"
  registry: "department-for-education"

enableDownloadResource: true
