database:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/openregister_java
  user: postgres
  password:

  #db connection properties
  initialSize: 1
  minSize: 1
  maxSize: 4

  properties:
    charSet: UTF-8

registers:
  register:
    credentials:
      user: sasine
      password: inhibition
    custodianName: Government Digital Service
    schema: register

server:
  requestLog:
    type: classic
    appenders:
      - type: logstash-console

  registerDefaultExceptionMappers: false
  adminConnectors:
    - type: http
      port: 9092

registerDomain: openregister.dev:8080

register: food-premises-rating

enableDownloadResource: true

schema: food-premises-rating

historyPageUrl: https://registers-history.herokuapp.com/school-eng

externalConfigDirectory: /tmp

downloadConfigs: true

enableRegisterDataDelete: true

# can be http: file s3: or classpath: url
fieldsYamlLocation: classpath://config/fields.yaml

registersYamlLocation: classpath://config/registers.yaml

similarRegisters:
  - address

indexes:
  - records

credentials:
  user: foo
  password: bar

# Logging settings.
logging:
  level: INFO
  # Logger-specific levels.
  loggers:
    "uk.gov": DEBUG
    "org.skife.jdbi.v2": TRACE
  appenders:
    - type: logstash-console
